version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw clean install -Pci

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.322
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.13
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
          
workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
  # See OKTA-634460
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
